"""
Markdown Reporter
Converts the structured API report dict into a human-readable Markdown document.
"""

from datetime import datetime


class MarkdownReporter:
    def __init__(self, report: dict):
        self.report = report
        self.meta = report.get("meta", {})
        self.summary = report.get("summary", {})
        self.endpoints = report.get("endpoints", [])

    def generate(self) -> str:
        lines: list[str] = []

        # Header
        lines += [
            f"# API Extraction Report — {self.meta.get('repo', 'Unknown Repo')}",
            "",
            f"> Generated by **Autonomous AI Agent v{self.meta.get('agent_version', '1.0')}**  ",
            f"> Repository: [{self.meta.get('repository', '')}]({self.meta.get('repository', '')})  ",
            f"> Branch: `{self.meta.get('branch', 'master')}`  ",
            f"> Extracted at: `{self.meta.get('extracted_at', '')}` (UTC)  ",
            f"> Files Scanned: **{self.meta.get('files_scanned', 0)}**  ",
            "",
            "---",
            "",
        ]

        # Summary table
        lines += [
            "## 📊 Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Endpoints | **{self.summary.get('total_endpoints', 0)}** |",
            f"| Auth-Required Endpoints | {self.summary.get('auth_required_count', 0)} |",
            f"| Files with Routes | {len(self.summary.get('source_files', []))} |",
            "",
        ]

        # By HTTP method
        by_method = self.summary.get("by_method", {})
        if by_method:
            lines += ["### By HTTP Method", "", "| Method | Count |", "|--------|-------|"]
            for method, count in sorted(by_method.items()):
                lines.append(f"| `{method}` | {count} |")
            lines.append("")

        # By tag/resource
        by_tag = self.summary.get("by_tag", {})
        if by_tag:
            lines += ["### By Resource Tag", "", "| Tag | Count |", "|-----|-------|"]
            for tag, count in sorted(by_tag.items(), key=lambda x: -x[1]):
                lines.append(f"| {tag} | {count} |")
            lines.append("")

        lines += ["---", ""]

        # Group endpoints by tag
        grouped: dict[str, list[dict]] = {}
        for ep in self.endpoints:
            tag = ep["tags"][0] if ep.get("tags") else "General"
            grouped.setdefault(tag, []).append(ep)

        lines += ["## 🔌 API Endpoints", ""]

        for tag in sorted(grouped.keys()):
            eps = grouped[tag]
            lines += [f"### {tag} ({len(eps)} endpoint{'s' if len(eps)!=1 else ''})", ""]

            for ep in eps:
                method = ep["method"]
                path = ep["path"]
                auth_badge = "🔒 " if ep.get("auth_required") else ""
                desc = ep.get("description", "")
                source = ep.get("source_file", "")
                line_no = ep.get("line_number", "")

                lines += [
                    f"#### {auth_badge}`{method}` `{path}`",
                    "",
                    f"**Description:** {desc}  " if desc else "",
                    f"**Source:** `{source}`" + (f" (line {line_no})" if line_no else "") + "  ",
                ]

                if ep.get("middlewares"):
                    lines.append(f"**Middlewares:** `{'`, `'.join(ep['middlewares'])}`  ")
                if ep.get("path_params"):
                    lines.append(f"**Path Params:** `{'`, `'.join(ep['path_params'])}`  ")

                lines.append("")

                # Request schema
                req = ep.get("request_schema", {})
                if req:
                    lines += ["**Request Schema:**", "```json", self._fmt_json(req), "```", ""]

                # Response schema
                resp = ep.get("response_schema", {})
                if resp:
                    lines += ["**Response Schema:**", "```json", self._fmt_json(resp), "```", ""]

                lines += ["---", ""]

        # Source files appendix
        source_files = self.summary.get("source_files", [])
        if source_files:
            lines += [
                "## 📁 Scanned Source Files with Routes",
                "",
            ]
            for sf in sorted(source_files):
                lines.append(f"- `{sf}`")
            lines.append("")

        return "\n".join(lines)

    def _fmt_json(self, obj: dict) -> str:
        import json
        return json.dumps(obj, indent=2)
